---
name: Linters

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.7', '3.0']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: run reviewdog
        env:
          reviewdog_github_api_token: ${{ secrets.github_token }}
        run: |
          reviewdog -fail-on-error -reporter=github-pr-review -runners=fasterer,rubocop

        # NOTE: check with: reviewdog -fail-on-error -reporter=github-pr-review -runners=fasterer -diff="git diff" -tee
